from typing import TypeVar, Generic, Protocol, Optional, Dict, List, Any

import asyncpg

T = TypeVar("T")


class DatabaseProtocol(Generic[T], Protocol):
    async def get(self, pool: asyncpg.Pool, **kwargs) -> Optional[T]: ...
    async def get_all(self, pool: asyncpg.Pool) -> List[T]: ...
    async def create(self, pool: asyncpg.Pool, **kwargs) -> bool: ...
    async def update(
        self, pool: asyncpg.Pool, search_data: Dict[str, Any], **kwargs
    ) -> bool: ...
    async def delete(self, pool: asyncpg.Pool, **kwargs) -> bool: ...
