services:
    bot:
      build: .
      restart: unless-stopped
      env_file:
        - .env
      network_mode: host
      volumes:
        - ./logs:/app/logs
        - ./logs_error:/app/logs_error
        - ./video_instructions:/app/video_instructions:ro
